import {
  Banknote,
  BookOpen,
  Boxes,
  Building2,
  FolderTree,
  Handshake,
  Package,
  Ruler,
  Tag,
  Truck,
  Users,
  UsersRound,
  Warehouse,
  UserSquare2,
} from "lucide-react";
import { P } from "@jst/permissions";
import { Badge } from "@jst/ui";
import { humanize } from "@jst/utilities";
import type { EntityConfig } from "../entity/types";
import { CURRENCY_LOOKUP, col, opts } from "./helpers";
import { ComponentsPanel } from "./ComponentsPanel";
import { makeQuickStatementPanel } from "../accounting/Statements";
import { AgentAccountsPanel, CustomerGroupMembersPanel, LocationsPanel, VariantsPanel } from "./panels";

const I = "h-4 w-4";

/* ============================================================ Customers */
export const customers: EntityConfig = {
  key: "customers",
  table: "customers",
  title: "Customers",
  singular: "Customer",
  description: "Customer accounts / farms. Link farms to a group for consolidated statements.",
  icon: <Users className={I} />,
  perms: { view: [P.customersView, P.customersViewAssigned], manage: P.customersManage },
  listSelect: "id, code, name, city, phone, contact_person, default_currency, is_also_supplier, is_active, group:customer_groups(name)",
  recordSelect:
    "id, code, name, group_id, contact_person, phone, whatsapp, email, address, city, ntn, strn, default_currency, payment_terms_days, notes, is_also_supplier, is_active, created_at, updated_at",
  searchColumns: ["name", "code", "city", "phone"],
  orderBy: { column: "name" },
  titleField: "name",
  subtitle: (r) => `${r.code}${r.city ? ` · ${r.city}` : ""}`,
  activeField: "is_active",
  columns: [
    col.code(),
    col.strong("name", "Customer", "contact_person"),
    col.rel("group", "group", "name", "Group / Farm parent", { hideBelow: "md" }),
    col.text("city", "City", { hideBelow: "md" }),
    col.text("phone", "Phone", { hideBelow: "sm" }),
    col.text("default_currency", "Cur.", { width: "60px", hideBelow: "lg" }),
    col.flag("is_also_supplier", "Party", "Also supplier"),
    col.active(),
  ],
  sections: [
    { code: "more", label: "Show Additional Customer Details", description: "Group, address, tax, terms, notes" },
    { code: "credit", label: "Credit Settings", description: "Credit limit", permission: P.customersViewFinancial },
  ],
  fields: [
    { name: "name", label: "Customer name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text", required: true, autoCode: true },
    { name: "contact_person", label: "Contact person", kind: "text" },
    { name: "phone", label: "Phone", kind: "phone" },
    { name: "city", label: "City", kind: "text" },
    { name: "is_also_supplier", label: "Also a supplier", kind: "checkbox", defaultValue: true, hint: "Keeps a linked supplier account with the same name and contact details (we also buy from this party)" },
    { name: "group_id", label: "Customer group", kind: "lookup", section: "more", lookup: { table: "customer_groups", label: "name", secondary: "code", filters: { is_active: true } }, hint: "Parent account for multi-farm customers" },
    { name: "whatsapp", label: "WhatsApp", kind: "phone", section: "more" },
    { name: "email", label: "Email", kind: "email", section: "more" },
    { name: "address", label: "Address", kind: "textarea", section: "more", span: 3 },
    { name: "ntn", label: "NTN", kind: "text", section: "more" },
    { name: "strn", label: "STRN", kind: "text", section: "more" },
    { name: "cnic", label: "CNIC", kind: "text", section: "more", restricted: { permission: P.customersViewFinancial, rpc: "customer_financial_details", param: "p_customer_id" } },
    { name: "notes", label: "Notes", kind: "textarea", section: "more", span: 3 },
    { name: "default_currency", label: "Default currency", kind: "lookup", section: "more", lookup: CURRENCY_LOOKUP, defaultValue: "PKR", required: true },
    { name: "payment_terms_days", label: "Payment terms (days)", kind: "number", section: "more", min: 0 },
    { name: "credit_limit", label: "Credit limit (PKR)", kind: "money", section: "credit", min: 0, restricted: { permission: P.customersViewFinancial, rpc: "customer_financial_details", param: "p_customer_id" } },
  ],  extraPanels: [{ key: "statement", label: "Statement", component: makeQuickStatementPanel("CUSTOMER") }],
};

export const customerGroups: EntityConfig = {
  key: "customer-groups",
  table: "customer_groups",
  title: "Customer Groups",
  singular: "Customer Group",
  description: "Parent accounts that own several farms / customer accounts.",
  icon: <UsersRound className={I} />,
  perms: { view: P.customersView, manage: P.customersManage },
  listSelect: "id, code, name, notes, is_active",
  recordSelect: "id, code, name, notes, is_active, created_at, updated_at",
  searchColumns: ["name", "code"],
  orderBy: { column: "name" },
  titleField: "name",
  subtitle: (r) => String(r.code),
  activeField: "is_active",
  dialogSize: "md",
  columns: [col.code(), col.strong("name", "Group"), col.text("notes", "Notes", { hideBelow: "md" }), col.active()],
  fields: [
    { name: "name", label: "Group name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text", required: true, autoCode: true },
    { name: "notes", label: "Notes", kind: "textarea", span: 3 },
  ],
  extraPanels: [{ key: "members", label: "Farms / Accounts", component: CustomerGroupMembersPanel }],
};

/* ============================================================ Suppliers */
export const suppliers: EntityConfig = {
  key: "suppliers",
  table: "suppliers",
  title: "Suppliers",
  singular: "Supplier",
  description: "Local and foreign suppliers. Currency is chosen per transaction; the default is convenience only.",
  icon: <Truck className={I} />,
  perms: { view: P.suppliersView, manage: P.suppliersManage },
  listSelect: "id, code, name, country, city, phone, default_currency, category, is_also_customer, is_active",
  recordSelect:
    "id, code, name, category, contact_person, phone, whatsapp, email, country, city, address, ntn, default_currency, payment_terms_days, notes, is_also_customer, is_active, created_at, updated_at",
  searchColumns: ["name", "code", "country", "city"],
  orderBy: { column: "name" },
  titleField: "name",
  subtitle: (r) => [r.code, r.country].filter(Boolean).join(" · "),
  activeField: "is_active",
  columns: [
    col.code(),
    col.strong("name", "Supplier", "category"),
    col.text("country", "Country", { hideBelow: "sm" }),
    col.text("city", "City", { hideBelow: "md" }),
    col.text("phone", "Phone", { hideBelow: "md" }),
    col.text("default_currency", "Cur.", { width: "60px" }),
    col.flag("is_also_customer", "Party", "Also customer"),
    col.active(),
  ],
  sections: [
    { code: "more", label: "Show Supplier Details", description: "Address, tax, terms, notes" },
    { code: "bank", label: "Banking Details", permission: P.suppliersViewFinancial },
  ],
  fields: [
    { name: "name", label: "Supplier name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text", required: true, autoCode: true },
    { name: "country", label: "Country", kind: "text", placeholder: "e.g. China" },
    { name: "phone", label: "Phone", kind: "phone" },
    { name: "default_currency", label: "Default currency", kind: "lookup", lookup: CURRENCY_LOOKUP, defaultValue: "PKR", required: true },
    { name: "is_also_customer", label: "Also a customer", kind: "checkbox", defaultValue: true, hint: "Keeps a linked customer account with the same name and contact details (we also sell to this party)" },
    { name: "category", label: "Category", kind: "text", section: "more" },
    { name: "contact_person", label: "Contact person", kind: "text", section: "more" },
    { name: "whatsapp", label: "WhatsApp / WeChat", kind: "text", section: "more" },
    { name: "email", label: "Email", kind: "email", section: "more" },
    { name: "city", label: "City", kind: "text", section: "more" },
    { name: "ntn", label: "NTN / Tax ID", kind: "text", section: "more" },
    { name: "payment_terms_days", label: "Payment terms (days)", kind: "number", section: "more", min: 0 },
    { name: "address", label: "Address", kind: "textarea", section: "more", span: 3 },
    { name: "notes", label: "Notes", kind: "textarea", section: "more", span: 3 },
    ...(["bank_name", "bank_account_title", "bank_account_number", "bank_swift"] as const).map((n) => ({
      name: n,
      label: humanize(n.replace("bank_", "")).replace("Swift", "SWIFT / Branch code"),
      kind: "text" as const,
      section: "bank",
      restricted: { permission: P.suppliersViewFinancial, rpc: "supplier_bank_details", param: "p_supplier_id" },
    })),
  ],  extraPanels: [{ key: "statement", label: "Statement", component: makeQuickStatementPanel("SUPPLIER") }],
};

/* ============================================================ Products */
export const products: EntityConfig = {
  key: "products",
  table: "products",
  title: "Products",
  singular: "Product",
  description: "Items, variants and stock-control settings.",
  icon: <Package className={I} />,
  perms: { view: P.productsView, manage: P.productsManage },
  listSelect:
    "id, sku, name, alias, has_variants, is_bundle, is_assembled, tracking_type, is_active, category:product_categories(name), uom:units_of_measure!products_base_uom_id_fkey(code), variants:product_variants(count)",
  recordSelect:
    "id, sku, name, alias, category_id, brand_id, base_uom_id, has_variants, tracking_type, is_bundle, is_assembled, allow_negative_stock, origin_country, weight_kg, dimensions, hs_code, reorder_level, description, is_active, created_at, updated_at",
  searchColumns: ["name", "sku", "alias"],
  orderBy: { column: "name" },
  titleField: "name",
  subtitle: (r) => [r.sku, r.alias].filter(Boolean).join(" · "),
  activeField: "is_active",
  dialogSize: "xl",
  columns: [
    col.code("sku", "SKU"),
    col.strong("name", "Product", "alias"),
    col.rel("category", "category", "name", "Category", { hideBelow: "md" }),
    col.rel("uom", "uom", "code", "Unit", { width: "70px" }),
    {
      key: "variants",
      header: "Variants",
      align: "right",
      hideBelow: "sm",
      width: "80px",
      cell: (r) => {
        const n = (r.variants as { count: number }[] | undefined)?.[0]?.count ?? 0;
        return r.has_variants ? n : <span className="text-ink-faint">—</span>;
      },
    },
    {
      key: "flags",
      header: "Type",
      hideBelow: "lg",
      cell: (r) => (
        <div className="flex gap-1">
          {r.is_bundle ? <Badge tone="info">Bundle</Badge> : null}
          {r.is_assembled ? <Badge tone="info">Assembled</Badge> : null}
          {r.tracking_type !== "NONE" ? <Badge>{humanize(String(r.tracking_type))}</Badge> : null}
        </div>
      ),
    },
    col.active(),
  ],
  sections: [{ code: "advanced", label: "Show Advanced Product Details", description: "Brand, origin, dimensions, stock controls" }],
  fields: [
    { name: "name", label: "Product name", kind: "text", required: true, span: 2 },
    { name: "sku", label: "SKU", kind: "text", required: true, autoCode: true },
    { name: "alias", label: "Alias / local name", kind: "text", hint: "Name used by staff or customers" },
    { name: "category_id", label: "Category", kind: "lookup", lookup: { table: "product_categories", label: "name", filters: { is_active: true } } },
    { name: "base_uom_id", label: "Base unit", kind: "lookup", required: true, lookup: { table: "units_of_measure", label: "code", secondary: "name", filters: { is_active: true } }, lockOnEdit: true, hint: "Stock is counted in this unit" },
    { name: "has_variants", label: "Has variants", kind: "checkbox", hint: "Stock is tracked per variant (e.g. 16-hole / 20-hole)" },
    { name: "is_bundle", label: "Bundle", kind: "checkbox", hint: "Commercial grouping of components" },
    { name: "is_assembled", label: "Assembled item", kind: "checkbox", hint: "Built from components (coolers, fans)" },
    { name: "brand_id", label: "Brand", kind: "lookup", section: "advanced", lookup: { table: "brands", label: "name", filters: { is_active: true } }, feature: "products.brands" },
    { name: "origin_country", label: "Origin", kind: "text", section: "advanced" },
    { name: "hs_code", label: "HS code", kind: "text", section: "advanced" },
    { name: "weight_kg", label: "Weight (kg)", kind: "number", section: "advanced", min: 0 },
    { name: "dimensions", label: "Dimensions", kind: "text", section: "advanced" },
    { name: "reorder_level", label: "Reorder level", kind: "number", section: "advanced", min: 0 },
    {
      name: "tracking_type",
      label: "Tracking",
      kind: "select",
      section: "advanced",
      required: true,
      defaultValue: "NONE",
      options: [
        { value: "NONE", label: "Quantity only" },
        { value: "PHYSICAL_UNIT", label: "By roll (each roll's length tracked)" },
      ],
      hint: "By roll: every receipt records each roll's length; sales and transfers cut from a roll (Inventory → Rolls)",
    },
    { name: "allow_negative_stock", label: "Allow negative stock", kind: "checkbox", section: "advanced", hint: "Only during onboarding / explicit policy" },
    { name: "description", label: "Description", kind: "textarea", section: "advanced", span: 3 },
  ],
  extraPanels: [
    { key: "variants", label: "Variants", component: VariantsPanel },
    { key: "components", label: "Components", component: ComponentsPanel, visible: (r) => Boolean(r.is_assembled || r.is_bundle) },
  ],
};

export const categories: EntityConfig = {
  key: "categories",
  table: "product_categories",
  title: "Product Categories",
  singular: "Category",
  icon: <FolderTree className={I} />,
  perms: { view: P.productsView, manage: P.productsManage },
  listSelect: "id, code, name, is_active, parent:parent_id(name)",
  recordSelect: "id, code, name, parent_id, is_active, created_at, updated_at",
  searchColumns: ["name", "code"],
  orderBy: { column: "name" },
  titleField: "name",
  activeField: "is_active",
  dialogSize: "md",
  columns: [col.code(), col.strong("name", "Category"), col.rel("parent", "parent", "name", "Parent"), col.active()],
  fields: [
    { name: "name", label: "Name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text" },
    { name: "parent_id", label: "Parent category", kind: "lookup", lookup: { table: "product_categories", label: "name" } },
  ],
};

export const brands: EntityConfig = {
  key: "brands",
  table: "brands",
  feature: "products.brands",
  title: "Brands",
  singular: "Brand",
  icon: <Tag className={I} />,
  perms: { view: P.productsView, manage: P.productsManage },
  listSelect: "id, name, is_active",
  recordSelect: "id, name, is_active, created_at, updated_at",
  searchColumns: ["name"],
  orderBy: { column: "name" },
  titleField: "name",
  activeField: "is_active",
  dialogSize: "md",
  columns: [col.strong("name", "Brand"), col.active()],
  fields: [{ name: "name", label: "Brand name", kind: "text", required: true, span: 2 }],
};

export const units: EntityConfig = {
  key: "units",
  table: "units_of_measure",
  title: "Units of Measure",
  singular: "Unit",
  icon: <Ruler className={I} />,
  perms: { view: P.productsView, manage: P.productsManage },
  listSelect: "id, code, name, allow_decimal, is_active",
  recordSelect: "id, code, name, allow_decimal, is_active, created_at, updated_at",
  searchColumns: ["code", "name"],
  orderBy: { column: "code" },
  titleField: "name",
  subtitle: (r) => String(r.code),
  activeField: "is_active",
  dialogSize: "md",
  columns: [col.code(), col.strong("name", "Unit"), col.flag("allow_decimal", "Decimals", "Allowed"), col.active()],
  fields: [
    { name: "code", label: "Code", kind: "text", required: true, placeholder: "PCS" },
    { name: "name", label: "Name", kind: "text", required: true, span: 2 },
    { name: "allow_decimal", label: "Allow decimal quantities", kind: "checkbox", hint: "e.g. KG, MTR" },
  ],
};

/* ============================================================ Warehouses */
export const warehouses: EntityConfig = {
  key: "warehouses",
  table: "warehouses",
  title: "Warehouses",
  singular: "Warehouse",
  description: "Adding a warehouse makes it available for stock and sales-order allocation automatically.",
  icon: <Warehouse className={I} />,
  perms: { view: P.warehousesView, manage: P.warehousesManage },
  listSelect: "id, code, name, address, phone, allow_negative_stock, is_active, branch:branches(name), locations:warehouse_locations(count)",
  recordSelect: "id, code, name, branch_id, address, phone, allow_negative_stock, is_active, created_at, updated_at",
  searchColumns: ["name", "code", "address"],
  orderBy: { column: "code" },
  titleField: "name",
  subtitle: (r) => String(r.code),
  activeField: "is_active",
  columns: [
    col.code(),
    col.strong("name", "Warehouse", "address"),
    col.rel("branch", "branch", "name", "Branch", { hideBelow: "md" }),
    { key: "loc", header: "Locations", align: "right", width: "90px", cell: (r) => (r.locations as { count: number }[])?.[0]?.count ?? 0 },
    col.flag("allow_negative_stock", "Neg. stock", "Allowed"),
    col.active(),
  ],
  fields: [
    { name: "name", label: "Warehouse name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text", required: true, autoCode: true },
    { name: "branch_id", label: "Branch", kind: "lookup", lookup: { table: "branches", label: "name", secondary: "code" } },
    { name: "phone", label: "Phone", kind: "phone" },
    { name: "allow_negative_stock", label: "Allow negative stock (onboarding)", kind: "checkbox", hint: "Lock once the physical baseline is counted" },
    { name: "address", label: "Address", kind: "textarea", span: 3 },
  ],
  extraPanels: [{ key: "locations", label: "Locations", component: LocationsPanel }],
  storageLocationParts: { columns: ["loc"], panels: ["locations"] },
};

/* ============================================================ Finance master */
export const bankAccounts: EntityConfig = {
  key: "bank-accounts",
  table: "bank_accounts",
  title: "Bank & Cash Accounts",
  singular: "Bank / Cash Account",
  icon: <Banknote className={I} />,
  perms: { view: P.banksView, manage: P.banksManage },
  listSelect: "id, code, name, account_kind, bank_name, account_number, currency, is_active, gl:chart_of_accounts(code, name)",
  recordSelect:
    "id, code, name, account_kind, bank_name, branch_name, account_title, account_number, iban, currency, gl_account_id, reconciled_until, is_active, created_at, updated_at",
  searchColumns: ["name", "code", "bank_name", "account_number"],
  orderBy: { column: "name" },
  titleField: "name",
  subtitle: (r) => [r.code, r.bank_name].filter(Boolean).join(" · "),
  activeField: "is_active",
  columns: [
    col.code(),
    col.strong("name", "Account", "bank_name"),
    col.enumBadge("account_kind", "Type"),
    col.text("account_number", "Account no.", { hideBelow: "md" }),
    col.text("currency", "Cur.", { width: "60px" }),
    { key: "gl", header: "GL account", hideBelow: "lg", cell: (r) => { const g = r.gl as { code: string; name: string } | null; return g ? `${g.code} · ${g.name}` : <span className="text-warning">Not linked</span>; } },
    col.active(),
  ],
  sections: [{ code: "bank", label: "Bank Details", description: "Branch, title, IBAN" }],
  fields: [
    { name: "name", label: "Account name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text", required: true, autoCode: true },
    { name: "account_kind", label: "Type", kind: "select", required: true, defaultValue: "BANK", options: opts(["BANK", "CASH", "WALLET"]) },
    { name: "currency", label: "Currency", kind: "lookup", required: true, defaultValue: "PKR", lookup: CURRENCY_LOOKUP },
    { name: "gl_account_id", label: "GL account", kind: "lookup", lookup: { table: "chart_of_accounts", label: "name", secondary: "code", filters: { is_group: false, account_type: "ASSET", is_active: true } }, hint: "Posting account in the chart of accounts" },
    { name: "bank_name", label: "Bank", kind: "text", section: "bank" },
    { name: "branch_name", label: "Branch", kind: "text", section: "bank" },
    { name: "account_title", label: "Account title", kind: "text", section: "bank" },
    { name: "account_number", label: "Account number", kind: "text", section: "bank" },
    { name: "iban", label: "IBAN", kind: "text", section: "bank", span: 2 },
  ],
};

export const chartOfAccounts: EntityConfig = {
  key: "chart-of-accounts",
  table: "chart_of_accounts",
  title: "Chart of Accounts",
  singular: "Account",
  description: "Balances are always derived from journal lines — never typed in.",
  icon: <BookOpen className={I} />,
  perms: { view: P.accountsView, manage: P.accountsManage },
  listSelect: "id, code, name, account_type, is_group, system_key, currency, is_active, parent:parent_id(code, name)",
  recordSelect: "id, code, name, account_type, parent_id, is_group, system_key, currency, description, is_active, created_at, updated_at",
  searchColumns: ["code", "name"],
  orderBy: { column: "code" },
  titleField: "name",
  subtitle: (r) => `${r.code} · ${humanize(String(r.account_type))}`,
  activeField: "is_active",
  status: (r) => (r.system_key ? <Badge tone="info">System · {String(r.system_key)}</Badge> : null),
  columns: [
    col.code("code", "Code"),
    { key: "name", header: "Account", cell: (r) => <span className={r.is_group ? "font-semibold" : ""}>{String(r.name)}</span> },
    col.enumBadge("account_type", "Type", { ASSET: "info", LIABILITY: "warning", EQUITY: "neutral", INCOME: "success", EXPENSE: "danger" }),
    { key: "parent", header: "Parent", hideBelow: "md", cell: (r) => { const p = r.parent as { code: string; name: string } | null; return p ? `${p.code} · ${p.name}` : ""; } },
    { key: "kind", header: "Kind", hideBelow: "sm", cell: (r) => (r.is_group ? <Badge>Group</Badge> : <span className="text-xs text-ink-muted">Posting</span>) },
    col.text("system_key", "System key", { hideBelow: "lg", className: "font-mono text-2xs" }),
    col.active(),
  ],
  fields: [
    { name: "code", label: "Code", kind: "text", required: true },
    { name: "name", label: "Account name", kind: "text", required: true, span: 2 },
    { name: "account_type", label: "Type", kind: "select", required: true, options: opts(["ASSET", "LIABILITY", "EQUITY", "INCOME", "EXPENSE"]), lockOnEdit: true },
    { name: "parent_id", label: "Parent (group)", kind: "lookup", lookup: { table: "chart_of_accounts", label: "name", secondary: "code", filters: { is_group: true } } },
    { name: "currency", label: "Currency (optional)", kind: "lookup", lookup: CURRENCY_LOOKUP },
    { name: "is_group", label: "Group account (no postings)", kind: "checkbox", lockOnEdit: true },
    { name: "description", label: "Description", kind: "textarea", span: 3 },
  ],
};

export const paymentAgents: EntityConfig = {
  key: "payment-agents",
  table: "payment_agents",
  title: "Payment Agents",
  singular: "Payment Agent",
  description: "Money exchanges / agents used to settle foreign suppliers.",
  icon: <Handshake className={I} />,
  perms: { view: P.paymentAgentsView, manage: P.paymentAgentsManage },
  listSelect: "id, code, name, contact_person, phone, city, is_active, accounts:payment_agent_accounts(currency)",
  recordSelect: "id, code, name, contact_person, phone, city, notes, is_active, created_at, updated_at",
  searchColumns: ["name", "code", "city"],
  orderBy: { column: "name" },
  titleField: "name",
  subtitle: (r) => String(r.code),
  activeField: "is_active",
  columns: [
    col.code(),
    col.strong("name", "Agent", "contact_person"),
    col.text("city", "City", { hideBelow: "md" }),
    col.text("phone", "Phone", { hideBelow: "sm" }),
    { key: "cur", header: "Sub-accounts", cell: (r) => <div className="flex gap-1">{((r.accounts as { currency: string }[]) ?? []).map((a) => <Badge key={a.currency}>{a.currency}</Badge>)}</div> },
    col.active(),
  ],
  fields: [
    { name: "name", label: "Agent name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Code", kind: "text", required: true, autoCode: true },
    { name: "contact_person", label: "Contact person", kind: "text" },
    { name: "phone", label: "Phone", kind: "phone" },
    { name: "city", label: "City", kind: "text" },
    { name: "notes", label: "Notes", kind: "textarea", span: 3 },
  ],
  extraPanels: [{ key: "accounts", label: "Currency Sub-accounts", component: AgentAccountsPanel }],
};

/* ============================================================ People */
export const employees: EntityConfig = {
  key: "employees",
  table: "employees",
  title: "Employees",
  singular: "Employee",
  description: "Staff master. Salary, payroll and assembly labour arrive with the HR stage.",
  icon: <UserSquare2 className={I} />,
  perms: { view: P.employeesView, manage: P.employeesManage },
  listSelect: "id, code, full_name, department, position, phone, joining_date, status",
  recordSelect:
    "id, code, full_name, user_id, department, position, phone, joining_date, status, reporting_manager_id, address, notes, created_at, updated_at",
  searchColumns: ["full_name", "code", "department", "position"],
  orderBy: { column: "full_name" },
  titleField: "full_name",
  subtitle: (r) => [r.code, r.position].filter(Boolean).join(" · "),
  activeField: null,
  status: (r) => <Badge tone={r.status === "ACTIVE" ? "success" : r.status === "LEFT" ? "neutral" : "warning"}>{humanize(String(r.status))}</Badge>,
  quickFilters: [
    { label: "Active", filters: { status: "ACTIVE" } },
    { label: "On leave", filters: { status: "ON_LEAVE" } },
    { label: "Left", filters: { status: "LEFT" } },
    { label: "All", filters: {} },
  ],
  columns: [
    col.code(),
    col.strong("full_name", "Employee", "position"),
    col.text("department", "Department", { hideBelow: "md" }),
    col.text("phone", "Phone", { hideBelow: "sm" }),
    col.enumBadge("status", "Status", { ACTIVE: "success", ON_LEAVE: "warning", SUSPENDED: "danger", LEFT: "neutral" }),
  ],
  sections: [{ code: "more", label: "Show Employment Details", description: "Joining, manager, login, ID" }],
  fields: [
    { name: "full_name", label: "Full name", kind: "text", required: true, span: 2 },
    { name: "code", label: "Employee code", kind: "text", required: true, autoCode: true },
    { name: "position", label: "Position", kind: "text" },
    { name: "department", label: "Department", kind: "text" },
    { name: "phone", label: "Phone", kind: "phone" },
    { name: "status", label: "Status", kind: "select", required: true, defaultValue: "ACTIVE", options: opts(["ACTIVE", "ON_LEAVE", "SUSPENDED", "LEFT"]) },
    { name: "joining_date", label: "Joining date", kind: "date", section: "more" },
    { name: "reporting_manager_id", label: "Reporting manager", kind: "lookup", section: "more", lookup: { table: "employees", label: "full_name", secondary: "code", filters: { status: "ACTIVE" } } },
    { name: "user_id", label: "ERP login (user)", kind: "lookup", section: "more", lookup: { table: "profiles", label: "full_name", secondary: "email", companyScoped: false } },
    { name: "cnic", label: "CNIC", kind: "text", section: "more", restricted: { permission: P.employeesViewRestricted, rpc: "employee_restricted_details", param: "p_employee_id" } },
    { name: "address", label: "Address", kind: "textarea", section: "more", span: 3 },
    { name: "notes", label: "Notes", kind: "textarea", section: "more", span: 3 },
  ],
};

export const branches: EntityConfig = {
  key: "branches",
  table: "branches",
  title: "Branches",
  singular: "Branch",
  icon: <Building2 className={I} />,
  perms: { view: P.settingsManage, manage: P.settingsManage },
  listSelect: "id, code, name, address, phone, is_active",
  recordSelect: "id, code, name, address, phone, is_active, created_at, updated_at",
  searchColumns: ["name", "code"],
  orderBy: { column: "code" },
  titleField: "name",
  activeField: "is_active",
  dialogSize: "md",
  columns: [col.code(), col.strong("name", "Branch", "address"), col.text("phone", "Phone"), col.active()],
  fields: [
    { name: "code", label: "Code", kind: "text", required: true },
    { name: "name", label: "Name", kind: "text", required: true, span: 2 },
    { name: "phone", label: "Phone", kind: "phone" },
    { name: "address", label: "Address", kind: "textarea", span: 3 },
  ],
};

export const ALL_ENTITIES = {
  customers,
  customerGroups,
  suppliers,
  products,
  categories,
  brands,
  units,
  warehouses,
  bankAccounts,
  chartOfAccounts,
  paymentAgents,
  employees,
  branches,
};

export const BoxesIcon = Boxes;
